# Generated by Django 5.2.12 on 2026-03-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('main_image', models.ImageField(upload_to='projects/main/')),
                ('year', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('hosted_link', models.URLField(blank=True)),
                ('final_title', models.CharField(max_length=200)),
                ('final_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
        ),
    ]
