# Generated by Django 5.2.9 on 2026-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
